// #define POT0 A0
// #define POT1 A1
// #define POT2 A2
// #define POT3 A3
// #define POT4 A4
// #define FADER_POT A5

// #define FADER_FORWARD 7
// #define FADER_REVERSE 8
// #define FADER_SPEED 6

// MCP Other
#define LED_MUTE 7
#define BUTTON_MUTE 6
#define LED_SOLO 5
#define BUTTON_SOLO 4

// MCP 0
#define TRACK_1_LED_MUTE 0
#define TRACK_1_LED_SOLO 1
#define TRACK_1_BUTTON_SELECT 2
#define TRACK_1_LED_SELECTED 3

#define TRACK_2_LED_MUTE 4
#define TRACK_2_LED_SOLO 5
#define TRACK_2_BUTTON_SELECT 6
#define TRACK_2_LED_SELECTED 7

#define TRACK_3_LED_MUTE 8
#define TRACK_3_LED_SOLO 9
#define TRACK_3_BUTTON_SELECT 10
#define TRACK_3_LED_SELECTED 11

#define TRACK_4_LED_MUTE 12
#define TRACK_4_LED_SOLO 13
#define TRACK_4_BUTTON_SELECT 14
#define TRACK_4_LED_SELECTED 15

// MCP 1
#define TRACK_5_BUTTON_SELECT 0
#define TRACK_5_LED_SELECTED 1
#define TRACK_5_LED_MUTE 2
#define TRACK_5_LED_SOLO 3

#define TRACK_6_BUTTON_SELECT 4
#define TRACK_6_LED_SELECTED 5
#define TRACK_6_LED_MUTE 6
#define TRACK_6_LED_SOLO 7

#define TRACK_7_BUTTON_SELECT 8
#define TRACK_7_LED_SELECTED 9
#define TRACK_7_LED_MUTE 10
#define TRACK_7_LED_SOLO 11

#define TRACK_8_BUTTON_SELECT 12
#define TRACK_8_LED_SELECTED 13
#define TRACK_8_LED_MUTE 14
#define TRACK_8_LED_SOLO 15